version: '3.5'

services:
  
  inotify:
    image: ghcr.io/killbus/docker-inotify:latest

    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /var/lib/docker/data/bind/config:/config
    - /var/lib/docker/data/bind/data:/data

    environment:
    - 'CONTAINER=bind'
    - 'VOLUMES=/config /data'
    - 'ACTION=restart'
    #- 'ACTION=kill'

    restart: always
